Check for tabs

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -22,6 +22,15 @@ jobs:
     - name: Check typos
       uses: crate-ci/typos@v1.32.0
 
+    - name: Check for tabs
+      run: |
+        git ls-files -z | while IFS= read -r -d '' file; do
+            if grep -I -P '\t' "$file"; then
+                echo "::error file=$file::File contains tabs. Please convert them to spaces."
+                exit 1
+            fi
+        done
+
   python-package:
     name: "Python: ${{ matrix.package }}"
     runs-on: ubuntu-24.04
